require('dotenv').config();

const config = {
  environment: process.env.NODE_ENV ? process.env.NODE_ENV : 'development',
  dev: process.env.NODE_ENV !== 'production' && process.env.NODE_ENV !== 'staging' && process.env.NODE_ENV !== 'preview',
  preview: process.env.NODE_ENV === 'preview',
  staging: process.env.NODE_ENV === 'staging',
  production: process.env.NODE_ENV === 'production',
  requestMaxPayloadSize: Number(process.env.REQUEST_MAX_PAYLOAD_SIZE) || (5 * 1048576),
  port: process.env.PORT || 3000,
  cors: process.env.CORS,
  baseUrlDashboard: process.env.BASE_URL_DASHBOARD,
  baseUrlApi: process.env.BASE_URL_API,
  tokenExpiresInSeconds: Number(process.env.TOKEN_EXPIRES_IN_SECONDS || 3600),
  tokenExpiresInMilliseconds: Number(process.env.TOKEN_EXPIRES_IN_SECONDS || 3600) * 1000,
  refreshTokenExpiresInSeconds: Number(process.env.REFRESH_TOKEN_EXPIRES_IN_SECONDS || 86400),
  refreshTokenExpiresInMilliseconds: Number(process.env.REFRESH_TOKEN_EXPIRES_IN_SECONDS
    || 86400) * 1000,
  dbUser: process.env.DB_USER,
  dbPassword: process.env.DB_PASSWORD,
  dbHost: process.env.DB_HOST,
  dbName: process.env.DB_NAME,
  authJwtSecret: process.env.AUTH_JWT_SECRET,
  authJwtSecretRefreshToken: process.env.AUTH_JWT_SECRET_REFRESH_TOKEN,
  authJwtSecondStepToken: process.env.AUTH_JWT_SECRET_SECOND_STEP,
  authBurstSms: process.env.AUTH_BURST_SMS,
  apiKeyBurstSms: process.env.API_KEY_BURST_SMS,
  apiSecretBurstSms: process.env.API_SECRET_BURST_SMS,
  apiKeyNexmo: process.env.API_KEY_NEXMO,
  apiSecretNexmo: process.env.API_SECRET_NEXMO,
  applicationIdNexmo: process.env.APPLICATION_ID_NEXMO,
  emailSlyBroadcast: process.env.EMAIL_SLYBROADCAST,
  passwordSlyBroadcast: process.env.PASSWORD_SLYBROADCAST,
  databaseUse: process.env.DATABASE_USE,
  webhookSlyBroadcastDevelopmentUrl: process.env.WEBHOOK_DEVELOPMENT_URL,
  userNameClickSend: process.env.USERNAME_CLICKSEND,
  apiKeyClickSend: process.env.API_KEY_CLICKSEND,
  apiKeySendGrid: process.env.SENDGRID_API_KEY,
  apiKeySendsei: process.env.API_KEY_SENDSEI,
  clientIdGoogle: process.env.CLIENT_ID_GOOGLE,
  clientSecretGoogle: process.env.CLIENT_SECRET_GOOGLE,
  telemarketerId: process.env.TELEMARKETER_ID,
  washOnlyUserId: process.env.WASH_ONLY_USER_ID,
  telemarketerPassword: process.env.TELEMARKETER_PASSWORD,
  clientReferenceId: process.env.CLIENT_REFERENCE_ID,
  authIdPlivo: process.env.AUTH_ID_PLIVO,
  authTokenPlivo: process.env.AUTH_TOKEN_PLIVO,
  sentryDns: process.env.SENTRY_DNS,
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET,
  urlReviewBaseInternal: process.env.URL_REVIEW_BASE_INTERNAL,
};

module.exports = { config };
